// <auto-generated />
using System;
using System.Collections.Generic;
using Kondix.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kondix.Infrastructure.Migrations
{
    [DbContext(typeof(KondixDbContext))]
    [Migration("20260404013155_AddWorkoutSessionsAndPhase1")]
    partial class AddWorkoutSessionsAndPhase1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gym")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kondix.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("AuthorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("author_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("DayId")
                        .HasColumnType("uuid")
                        .HasColumnName("day_id");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid")
                        .HasColumnName("routine_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("RoutineId", "DayId")
                        .HasDatabaseName("ix_comments_routine_id_day_id");

                    b.ToTable("comments", "gym");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.Day", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid")
                        .HasColumnName("routine_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_days");

                    b.HasIndex("RoutineId")
                        .HasDatabaseName("ix_days_routine_id");

                    b.ToTable("days", "gym");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Tempo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tempo");

                    b.Property<string>("VideoSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("None")
                        .HasColumnName("video_source");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("video_url");

                    b.HasKey("Id")
                        .HasName("pk_exercises");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_exercises_group_id");

                    b.ToTable("exercises", "gym");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.ExerciseGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("DayId")
                        .HasColumnType("uuid")
                        .HasColumnName("day_id");

                    b.Property<string>("GroupType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Single")
                        .HasColumnName("group_type");

                    b.Property<int>("RestSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("rest_seconds");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_exercise_groups");

                    b.HasIndex("DayId")
                        .HasDatabaseName("ix_exercise_groups_day_id");

                    b.ToTable("exercise_groups", "gym");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.ExerciseSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("rest_seconds");

                    b.Property<string>("SetType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Effective")
                        .HasColumnName("set_type");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("TargetReps")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_reps");

                    b.Property<int?>("TargetRpe")
                        .HasColumnType("integer")
                        .HasColumnName("target_rpe");

                    b.Property<string>("TargetWeight")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_weight");

                    b.HasKey("Id")
                        .HasName("pk_exercise_sets");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("ix_exercise_sets_exercise_id");

                    b.ToTable("exercise_sets", "gym");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.Routine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("trainer_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_routines");

                    b.HasIndex("TrainerId")
                        .HasDatabaseName("ix_routines_trainer_id");

                    b.ToTable("routines", "gym");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.RoutineAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid")
                        .HasColumnName("routine_id");

                    b.PrimitiveCollection<List<int>>("ScheduledDays")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer[]")
                        .HasColumnName("scheduled_days")
                        .HasDefaultValueSql("ARRAY[]::integer[]");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_routine_assignments");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_routine_assignments_student_id");

                    b.HasIndex("RoutineId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_routine_assignments_routine_id_student_id");

                    b.ToTable("routine_assignments", "gym");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.SetLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActualReps")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("actual_reps");

                    b.Property<int?>("ActualRpe")
                        .HasColumnType("integer")
                        .HasColumnName("actual_rpe");

                    b.Property<string>("ActualWeight")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("actual_weight");

                    b.Property<bool>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("completed");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid")
                        .HasColumnName("routine_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid?>("SetId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_id");

                    b.Property<string>("SnapshotExerciseName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("snapshot_exercise_name");

                    b.Property<string>("SnapshotTargetReps")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("snapshot_target_reps");

                    b.Property<string>("SnapshotTargetWeight")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("snapshot_target_weight");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_set_logs");

                    b.HasIndex("SetId")
                        .HasDatabaseName("ix_set_logs_set_id");

                    b.HasIndex("SessionId", "SetId")
                        .IsUnique()
                        .HasDatabaseName("ix_set_logs_session_id_set_id");

                    b.HasIndex("StudentId", "RoutineId")
                        .HasDatabaseName("ix_set_logs_student_id_routine_id");

                    b.ToTable("set_logs", "gym");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("ActiveTrainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_trainer_id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<Guid>("CelvoGuardUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("celvo_guard_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.HasIndex("ActiveTrainerId")
                        .HasDatabaseName("ix_students_active_trainer_id");

                    b.HasIndex("CelvoGuardUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_students_celvo_guard_user_id");

                    b.ToTable("students", "gym");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.StudentInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("AcceptedByStudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_by_student_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("character varying(88)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("trainer_id");

                    b.HasKey("Id")
                        .HasName("pk_student_invitations");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_student_invitations_token_hash");

                    b.HasIndex("TrainerId")
                        .HasDatabaseName("ix_student_invitations_trainer_id");

                    b.ToTable("student_invitations", "gym");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.Trainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("bio");

                    b.Property<Guid>("CelvoGuardUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("celvo_guard_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_approved");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_trainers");

                    b.HasIndex("CelvoGuardUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_trainers_celvo_guard_user_id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_trainers_tenant_id");

                    b.ToTable("trainers", "gym");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.TrainerNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_pinned");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("trainer_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_trainer_notes");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_trainer_notes_student_id");

                    b.HasIndex("TrainerId", "StudentId")
                        .HasDatabaseName("ix_trainer_notes_trainer_id_student_id");

                    b.ToTable("trainer_notes", "gym");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.TrainerStudent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("trainer_id");

                    b.HasKey("Id")
                        .HasName("pk_trainer_students");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_trainer_students_student_id");

                    b.HasIndex("TrainerId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_trainer_students_trainer_id_student_id");

                    b.ToTable("trainer_students", "gym");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("DayId")
                        .HasColumnType("uuid")
                        .HasColumnName("day_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid")
                        .HasColumnName("routine_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_workout_sessions");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_workout_sessions_assignment_id");

                    b.HasIndex("DayId")
                        .HasDatabaseName("ix_workout_sessions_day_id");

                    b.HasIndex("RoutineId")
                        .HasDatabaseName("ix_workout_sessions_routine_id");

                    b.HasIndex("StudentId", "AssignmentId")
                        .HasDatabaseName("ix_workout_sessions_student_id_assignment_id");

                    b.HasIndex("StudentId", "RoutineId", "DayId")
                        .HasDatabaseName("ix_workout_sessions_student_id_routine_id_day_id");

                    b.ToTable("workout_sessions", "gym");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.Day", b =>
                {
                    b.HasOne("Kondix.Domain.Entities.Routine", "Routine")
                        .WithMany("Days")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_days_routines_routine_id");

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.Exercise", b =>
                {
                    b.HasOne("Kondix.Domain.Entities.ExerciseGroup", "Group")
                        .WithMany("Exercises")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercises_exercise_groups_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.ExerciseGroup", b =>
                {
                    b.HasOne("Kondix.Domain.Entities.Day", "Day")
                        .WithMany("ExerciseGroups")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_groups_days_day_id");

                    b.Navigation("Day");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.ExerciseSet", b =>
                {
                    b.HasOne("Kondix.Domain.Entities.Exercise", "Exercise")
                        .WithMany("Sets")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_sets_exercises_exercise_id");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.Routine", b =>
                {
                    b.HasOne("Kondix.Domain.Entities.Trainer", "Trainer")
                        .WithMany("Routines")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_routines_trainers_trainer_id");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.RoutineAssignment", b =>
                {
                    b.HasOne("Kondix.Domain.Entities.Routine", "Routine")
                        .WithMany("Assignments")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_routine_assignments_routines_routine_id");

                    b.HasOne("Kondix.Domain.Entities.Student", "Student")
                        .WithMany("RoutineAssignments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_routine_assignments_students_student_id");

                    b.Navigation("Routine");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.SetLog", b =>
                {
                    b.HasOne("Kondix.Domain.Entities.WorkoutSession", "Session")
                        .WithMany("SetLogs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_set_logs_workout_sessions_session_id");

                    b.HasOne("Kondix.Domain.Entities.ExerciseSet", "Set")
                        .WithMany("SetLogs")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_set_logs_exercise_sets_set_id");

                    b.HasOne("Kondix.Domain.Entities.Student", "Student")
                        .WithMany("SetLogs")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_set_logs_students_student_id");

                    b.Navigation("Session");

                    b.Navigation("Set");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.Student", b =>
                {
                    b.HasOne("Kondix.Domain.Entities.Trainer", "ActiveTrainer")
                        .WithMany()
                        .HasForeignKey("ActiveTrainerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_students_trainers_active_trainer_id");

                    b.Navigation("ActiveTrainer");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.StudentInvitation", b =>
                {
                    b.HasOne("Kondix.Domain.Entities.Trainer", "Trainer")
                        .WithMany("Invitations")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_invitations_trainers_trainer_id");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.TrainerNote", b =>
                {
                    b.HasOne("Kondix.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trainer_notes_students_student_id");

                    b.HasOne("Kondix.Domain.Entities.Trainer", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trainer_notes_trainers_trainer_id");

                    b.Navigation("Student");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.TrainerStudent", b =>
                {
                    b.HasOne("Kondix.Domain.Entities.Student", "Student")
                        .WithMany("TrainerStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trainer_students_students_student_id");

                    b.HasOne("Kondix.Domain.Entities.Trainer", "Trainer")
                        .WithMany("TrainerStudents")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trainer_students_trainers_trainer_id");

                    b.Navigation("Student");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.WorkoutSession", b =>
                {
                    b.HasOne("Kondix.Domain.Entities.RoutineAssignment", "Assignment")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workout_sessions_routine_assignments_assignment_id");

                    b.HasOne("Kondix.Domain.Entities.Day", "Day")
                        .WithMany()
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workout_sessions_days_day_id");

                    b.HasOne("Kondix.Domain.Entities.Routine", "Routine")
                        .WithMany()
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workout_sessions_routines_routine_id");

                    b.HasOne("Kondix.Domain.Entities.Student", "Student")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workout_sessions_students_student_id");

                    b.Navigation("Assignment");

                    b.Navigation("Day");

                    b.Navigation("Routine");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.Day", b =>
                {
                    b.Navigation("ExerciseGroups");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.Exercise", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.ExerciseGroup", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.ExerciseSet", b =>
                {
                    b.Navigation("SetLogs");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.Routine", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Days");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.RoutineAssignment", b =>
                {
                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.Student", b =>
                {
                    b.Navigation("RoutineAssignments");

                    b.Navigation("SetLogs");

                    b.Navigation("TrainerStudents");

                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.Trainer", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Routines");

                    b.Navigation("TrainerStudents");
                });

            modelBuilder.Entity("Kondix.Domain.Entities.WorkoutSession", b =>
                {
                    b.Navigation("SetLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
